// svelte/11.router/src/App.svelte
<script>
  import { Router, Route, Link } from "svelte-navigator";
</script>

<Router>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary px-0 py-1">
      <div class="navbar-nav">
        <Link class="nav-item nav-link" to="/">Home</Link>
        <Link class="nav-item nav-link" to="/about">About</Link>
      </div>
    </nav>
  </header>
  <main>
    <Route path="/">
      <h1>Home</h1>
    </Route>
    <Route path="/about">
      <h1>About</h1>
    </Route>
  </main>
</Router>

// reactjs/11.router/src/App.js
import {
  Link,
  Routes,
  Route
} from "react-router-dom";

function Home() {
  return <h1>Home</h1>;
}

function About() {
  return <h1>About</h1>;
}

function App() {
  return(
    <>
      <nav className="navbar navbar-expand-lg navbar-dark bg-primary px-0 py-1">
        <div className="navbar-nav">
          <Link className="nav-item nav-link" to="/">Home</Link>
          <Link className="nav-item nav-link" to="/about">About</Link>
        </div>
      </nav>
      
      <Routes>
        <Route path="/" element={<Home />}/>
        <Route path="/about" element={<About />}/>
      </Routes>
    </>
  )
}

export default App;
